
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bzeheatnix
 */
public class ShopifyConverter extends javax.swing.JFrame {

    CSVR csvr = new CSVR();
    Object inputValue = "";
    /**
     * Creates new form ShopifyConverter
     */
    public ShopifyConverter() throws UnsupportedLookAndFeelException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        initComponents();
        setTitle("Shopify CSV Converter");
        // Set System L&F
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageURLBtn = new javax.swing.JButton();
        convertToCSVBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageURLBtn.setText("Setup Image URL");
        imageURLBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageURLBtnMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageURLBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageURLBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageURLBtnMouseEntered(evt);
            }
        });
        imageURLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageURLBtnActionPerformed(evt);
            }
        });

        convertToCSVBtn.setText("Convert to Shopify CSV Format");
        convertToCSVBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertToCSVBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(imageURLBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(convertToCSVBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(47, 47, 47)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(imageURLBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(convertToCSVBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageURLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageURLBtnActionPerformed
        inputValue = JOptionPane.showInputDialog(null, "Remote images URL.", "Images URL Setup", JOptionPane.INFORMATION_MESSAGE, null, null,  "http://example.com/");
        System.out.println(inputValue);
    }//GEN-LAST:event_imageURLBtnActionPerformed

    private void convertToCSVBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertToCSVBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select a valid csv file");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV files (*.csv)", "csv");
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int returnVal = fileChooser.showOpenDialog(null);
        File file = fileChooser.getSelectedFile();
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(null, "Succesfully convertion.", "information", JOptionPane.INFORMATION_MESSAGE);
            try {
                csvr.convertToCSV(file.getPath(), inputValue);
            } catch (IOException ex) {
                Logger.getLogger(ShopifyConverter.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (returnVal == JFileChooser.CANCEL_OPTION) {
            
        }
    }//GEN-LAST:event_convertToCSVBtnActionPerformed

    private void imageURLBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageURLBtnMouseEntered
        // TODO add your handling code here:
        //imageURLBtn.setBackground(Color.BLUE);
    }//GEN-LAST:event_imageURLBtnMouseEntered

    private void imageURLBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageURLBtnMouseExited
        imageURLBtn.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_imageURLBtnMouseExited

    private void imageURLBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageURLBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageURLBtnMousePressed

    private void imageURLBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageURLBtnMouseClicked
        
    }//GEN-LAST:event_imageURLBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopifyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopifyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopifyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopifyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new ShopifyConverter().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ShopifyConverter.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ShopifyConverter.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ShopifyConverter.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ShopifyConverter.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertToCSVBtn;
    private javax.swing.JButton imageURLBtn;
    // End of variables declaration//GEN-END:variables
}
